pub const LIST: &[(&str, &str)] = &[
    ("Apache", "Apache config"),
    ("Arduino", "Arduino"),
    ("AutoHotkey", "AutoHotkey"),
    ("Awk", "Awk"),
    ("BASIC", "BASIC"),
    ("Bash", "Bash"),
    ("Batch", "Batch file"),
    ("Brainfuck", "Brainfuck"),
    ("C", "C"),
    ("C#", "C#"),
    ("C++", "C++"),
    ("CMake", "CMake"),
    ("CSS", "CSS"),
    ("Clojure", "Clojure"),
    ("CoffeeScript", "CoffeeScript"),
    ("Crystal", "Crystal"),
    ("D", "D"),
    ("Dart", "Dart"),
    ("Diff", "Diff"),
    ("Dockerfile", "Dockerfile"),
    ("Elixir", "Elixir"),
    ("Elm", "Elm"),
    ("Erlang", "Erlang"),
    ("F#", "F#"),
    ("GLSL", "GLSL"),
    ("Go", "Go"),
    ("Gradle", "Gradle"),
    ("Groovy", "Groovy"),
    ("HAML", "HAML"),
    ("HTML", "HTML"),
    ("HTTP", "HTTP"),
    ("Handlebars", "Handlebars"),
    ("Haskell", "Haskell"),
    ("Haxe", "Haxe"),
    ("INI", "INI"),
    ("JSON", "JSON"),
    ("Java", "Java"),
    ("JavaScript", "JavaScript"),
    ("Julia", "Julia"),
    ("Kotlin", "Kotlin"),
    ("LaTeX", "LaTeX"),
    ("Less", "Less"),
    ("Lisp", "Lisp"),
    ("Lua", "Lua"),
    ("Makefile", "Makefile"),
    ("Markdown", "Markdown"),
    ("Matlab", "Matlab"),
    ("Nginx", "Nginx config"),
    ("Nim", "Nim"),
    ("Nix", "Nix"),
    ("OCaml", "OCaml"),
    ("Objective-C", "Objective-C"),
    ("OpenSCAD", "OpenSCAD"),
    ("PHP", "PHP"),
    ("Perl", "Perl"),
    ("Plain", "Plain text"),
    ("PostgreSQL", "PostgreSQL"),
    ("PowerShell", "PowerShell"),
    ("Processing", "Processing"),
    ("Prolog", "Prolog"),
    ("Puppet", "Puppet"),
    ("Python", "Python"),
    ("R", "R"),
    ("ReasonML", "ReasonML"),
    ("Ruby", "Ruby"),
    ("Rust", "Rust"),
    ("SCSS", "SCSS"),
    ("SQL", "SQL"),
    ("Scala", "Scala"),
    ("Scheme", "Scheme"),
    ("Shell", "Shell Session"),
    ("Swift", "Swift"),
    ("TOML", "TOML"),
    ("Twig", "Twig"),
    ("TypeScript", "TypeScript"),
    ("VB.NET", "VB.NET"),
    ("VBScript", "VBScript"),
    ("VimL", "VimL"),
    ("XML", "XML"),
    ("YAML", "YAML"),
];

pub const PLAIN_TEXT_INDEX: usize = 55;
